import os

import aiohttp
import discord
from discord import app_commands
from dotenv import load_dotenv

from database import initialize_database, is_server_linked, get_linked_server
from server import link_dashboard_server
from backup import backup_command
from verification import send_verification_embed
from restore import restore_command
from announce import announce_verified
from customize import customize_bot


load_dotenv()

DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")
COMVERIFY_API_URL = os.getenv(
    "COMVERIFY_API_URL",
    "https://comverifydas-yjyffaj4.manus.space"
).rstrip("/")

if not DISCORD_TOKEN:
    raise RuntimeError(
        "DISCORD_TOKEN is not set. Add it to your environment variables."
    )


async def connect_server(project_key: str, guild: discord.Guild, owner_id: int):
    """Send the raw dashboard project key to the live ComVerify API."""
    payload = {
        "project_key": project_key.strip(),
        "guild_id": str(guild.id),
        "guild_name": guild.name,
        "owner_id": str(owner_id),
    }
    timeout = aiohttp.ClientTimeout(total=15)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.post(
            f"{COMVERIFY_API_URL}/api/login",
            json=payload,
            headers={"Content-Type": "application/json"},
        ) as response:
            try:
                body = await response.json()
            except Exception:
                body = {"success": False, "error": await response.text()}
            return response.status, body


initialize_database()


class ComVerify(discord.Client):
    def __init__(self):
        intents = discord.Intents.default()
        super().__init__(intents=intents)
        self.tree = app_commands.CommandTree(self)

    async def setup_hook(self):
        await self.tree.sync()

    async def on_ready(self):
        print("--------------------------------")
        print("        ComVerify Online")
        print("--------------------------------")
        print(f"Bot: {self.user}")
        print(f"Bot ID: {self.user.id}")
        print(f"Servers: {len(self.guilds)}")
        print("Dashboard API:", COMVERIFY_API_URL)
        print("Slash commands synced.")
        print("--------------------------------")


bot = ComVerify()


@bot.tree.command(name="ping", description="Check if ComVerify is online.")
async def ping(interaction: discord.Interaction):
    await interaction.response.send_message(
        f"🏓 Pong! `{round(bot.latency * 1000)}ms`"
    )


@bot.tree.command(name="help", description="Show ComVerify's commands.")
async def help_command(interaction: discord.Interaction):
    embed = discord.Embed(
        title="ComVerify",
        description="Community verification, member backup and server recovery.",
        color=discord.Color.blurple(),
    )
    embed.add_field(
        name="Getting Started",
        value="`/login` — Connect this server to a ComVerify project.",
        inline=False,
    )
    embed.add_field(
        name="Commands",
        value=(
            "`/ping` — Check bot latency\n"
            "`/help` — Show this menu\n"
            "`/login` — Connect your server\n"
            "`/verify` — Send verification panel\n"
            "`/backup` — Create a backup\n"
            "`/restore` — Restore a backup\n"
            "`/announce` — Announce to verified members\n"
            "`/customize` — Customize ComVerify"
        ),
        inline=False,
    )
    await interaction.response.send_message(embed=embed, ephemeral=True)


@bot.tree.command(
    name="login",
    description="Connect this server using a key generated by the ComVerify dashboard.",
)
@app_commands.describe(project_key="The raw project key copied from the ComVerify dashboard.")
async def login(interaction: discord.Interaction, project_key: str):
    if interaction.guild is None:
        await interaction.response.send_message(
            "❌ This command can only be used inside a Discord server.",
            ephemeral=True,
        )
        return
    if not interaction.user.guild_permissions.administrator:
        await interaction.response.send_message(
            "❌ You need Administrator permissions to connect this server.",
            ephemeral=True,
        )
        return
    if not project_key.strip():
        await interaction.response.send_message(
            "❌ Paste the project key generated by the ComVerify dashboard.",
            ephemeral=True,
        )
        return

    await interaction.response.defer(ephemeral=True)
    try:
        status, result = await connect_server(
            project_key, interaction.guild, interaction.user.id
        )
    except Exception as error:
        print(f"Login API error: {error}")
        await interaction.followup.send(
            "❌ I couldn't reach the ComVerify dashboard. "
            "Check COMVERIFY_API_URL and confirm the bot has internet access.",
            ephemeral=True,
        )
        return

    if status == 200 and result.get("success"):
        link_dashboard_server(
            project_id=int(result["project_id"]),
            project_name=result.get("project_name", "ComVerify project"),
            owner_id=str(interaction.user.id),
            guild_id=str(interaction.guild.id),
            guild_name=interaction.guild.name,
            dashboard_server_id=int(result.get("server_id", 0)) or None,
            project_key=project_key.strip(),
        )
        await interaction.followup.send(
            "✅ **Server connected!**\n\n"
            f"This server is now linked to **{result.get('project_name', 'ComVerify project')}**.",
            ephemeral=True,
        )
        return

    if status == 401:
        message = "❌ That project key is invalid, revoked, or expired. Copy a fresh key from the dashboard."
    elif status == 409:
        message = f"❌ {result.get('error', 'This server cannot be linked to that project.')}"
    elif status == 429:
        message = "⏳ Too many login attempts. Please try again later."
    else:
        message = f"❌ Dashboard response `{status}`: {result.get('error', 'Unknown error.')}"
    await interaction.followup.send(message, ephemeral=True)


@bot.tree.command(name="verify", description="Send the ComVerify verification panel.")
async def verify(interaction: discord.Interaction):
    if interaction.guild is None:
        await interaction.response.send_message("❌ Use this command inside a server.", ephemeral=True)
        return
    if not interaction.user.guild_permissions.administrator:
        await interaction.response.send_message("❌ Administrator permission required.", ephemeral=True)
        return
    await send_verification_embed(interaction)


@bot.tree.command(name="backup", description="Create a ComVerify server backup.")
async def backup(interaction: discord.Interaction):
    await backup_command(interaction)


@bot.tree.command(name="restore", description="Restore a ComVerify backup.")
@app_commands.describe(backup_id="Optional dashboard backup ID; defaults to the latest backup.")
async def restore(interaction: discord.Interaction, backup_id: int | None = None):
    await restore_command(interaction, backup_id)


@bot.tree.command(name="announce", description="Send an announcement to verified members.")
@app_commands.describe(message="The announcement you want to send.")
async def announce(interaction: discord.Interaction, message: str):
    await announce_verified(interaction, message)


@bot.tree.command(name="customize", description="Customize ComVerify for this server.")
@app_commands.describe(display_name="The display name ComVerify should use in this server.")
async def customize(interaction: discord.Interaction, display_name: str):
    await customize_bot(interaction, display_name)


bot.run(DISCORD_TOKEN)
